---
graph_customization:
  fillcolor: lemonchiffon
  color: darkgoldenrod

FRONTEND:
  nginx:
    vhost: www
  dependencies:
    - component: PROJECT.APPLICATION2.DATABASE
      service: mariadb
    - component: PROJECT.APPLICATION1.DATABASE
      service: mariadb

BACKEND:
  nginx:
    vhost: back
  dependencies:
    - component: PROJECT.APPLICATION2.DATABASE
      service: mariadb

DATABASE:
  mariadb:
    name: test
