# Flat user-data usage

project_website1_database_mariadb_user=${project_website1_database_mariadb_user}
project_website1_database_mariadb_password=${project_website1_database_mariadb_password}
project_website1_database_mariadb_port=${project_website1_database_mariadb_port}
project_website1_database_mariadb_dns=${project_website1_database_mariadb_dns}
project_website1_database_mariadb_database=${project_website1_database_mariadb_database}
